[package]
name = "a_level_project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
ego-tree = "0.6.2"
fastrand = "2.0.1"
graphvis_ego_tree = "0.3.4"
monte_carlo = "0.1.0"
raylib = "3.7.0"
